extends Node

signal BUL_create_bulletin
signal BUL_destroy_bulletin

signal INV_try_to_pickup_item
signal INV_ask_to_update_inventory
signal INV_inventory_updated
signal INV_hotbar_updated
signal INV_switch_two_item_indexes
signal INV_set_description_label
signal INV_set_extra_info_label
signal INV_add_item
signal INV_delete_crafting_blueprints_costs
signal INV_delete_item_by_index
signal INV_add_item_by_index

signal PLY_freeze_player
signal PLY_unfreeze_player
signal PLY_change_energy
signal PLY_energy_updated
signal PLY_change_health
signal PLY_health_updated

signal EQU_hotkey_pressed
signal EQU_equip_item
signal EQU_unequip_item
signal EQU_active_hotbar_slot_updated
signal EQU_delete_equipped_item

signal SPA_spawn_scene
