extends Node

signal BUL_create_bulletin
signal BUL_destroy_bulletin

signal INV_try_to_pickup_item
signal INV_ask_to_update_inventory
signal INV_inventory_updated
signal INV_switch_two_item_indexes

signal PLY_freeze_player
signal PLY_unfreeze_player
